### ISSUE TITLE
Instapay egypt 1.7.0 latest update detects root

### ISSUE THREAD

**Issue by hexman1999** [snake-4/Zygisk-Assistant#44]
**Describe the bug**
Instapay egypt 1.6.3 doesn't detect root with zygisk assistant, the next update 1.7.0 it crashes and detects root, I tried to turn off all modules but zygisk assistant and still detected

 - Device: Xiaomi Redmi note 10 Pro
 - OS: android 13 miui 14
 - Version of Magisk, KSU or APatch: 27002 alpha magisk
 - Other Root Module(s): -play integrity - bootloop saver- systemless hosts
 - LSPosed Module(s): None

**Comment by SEAL300** [comment]
Process: com.egyptianbanks.instapay
PID: 20772
UID: 10305
Frozen: false
Flags: 0x20c83e44
Package: com.egyptianbanks.instapay v35 (1.7.0)
Foreground: Yes
Process-Runtime: 5082
Build: samsung/a22nsxx/a22:13/TP1A.220624.014/A225FXXS8DXA1:user/release-keys
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getString(int)' on a null object reference
 at android.app.ActivityThread.installProvider(ActivityThread.java:8333)
 at android.app.ActivityThread.installContentProviders(ActivityThread.java:7833)
 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7582)
 at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2400)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:226)
 at android.os.Looper.loop(Looper.java:313)
 at android.app.ActivityThread.main(ActivityThread.java:8762)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getString(int)' on a null object reference
 at com.olive.insta_pay.activity.BaseActivity$Companion.showAlert(:325)
 at kotlinx.coroutines.internal.ThreadLocalKt.$$a(:1319)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.google.firebase.provider.FirebaseInitProvider.onCreate(:1825)
 at android.content.ContentProvider.attachInfo(ContentProvider.java:2522)
 at android.content.ContentProvider.attachInfo(ContentProvider.java:2492)
 at com.google.firebase.provider.FirebaseInitProvider.attachInfo(:45)
 at android.app.ActivityThread.installProvider(ActivityThread.java:8328)
 ... 11 more

**Comment by AbdelrahmanMohamedDesoky** [comment]
same behavior exactly here.

**Comment by keosh1** [comment]
+1

**Comment by AbdelrahmanMohamedDesoky** [comment]
I installed KSU/ZygiskNext/PlayIntegrityFix/Shamiko and it works fine now, don't know why it didn't work with kitsune

**Comment by hexman1999** [comment]
> I installed KSU/ZygiskNext/PlayIntegrityFix/Shamiko and it works fine now, don't know why it didn't work with kitsune

It worked for me with alpha+zygisk next+shamiko from the telegram channel 

Btw shamiko developer said it won't work in kitsune because of different way of loading zygisk

**Comment by keosh1** [comment]
Please my friends can both of you try to install klivvr app because instapay work now but klivvr no 
I want to know which setup will make both works ☺️ 
Ty btw 🥰

**Comment by keosh1** [comment]
> I installed KSU/ZygiskNext/PlayIntegrityFix/Shamiko and it works fine now, don't know why it didn't work with kitsune

If you can try klivvr app too and gimme feedback

**Comment by keosh1** [comment]
> > I installed KSU/ZygiskNext/PlayIntegrityFix/Shamiko and it works fine now, don't know why it didn't work with kitsune
> 
> It worked for me with alpha+zygisk next+shamiko from the telegram channel 
> 
> Btw shamiko developer said it won't work in kitsune because of different way of loading zygisk 

If you can try klivvr app too and gimme feedback

**Comment by SEAL300** [comment]
> > I installed KSU/ZygiskNext/PlayIntegrityFix/Shamiko and it works fine now, don't know why it didn't work with kitsune
> 
> It worked for me with alpha+zygisk next+shamiko from the telegram channel
> 
> Btw shamiko developer said it won't work in kitsune because of different way of loading zygisk

Could you attach the link for them😅

**Comment by hexman1999** [comment]
> > > I installed KSU/ZygiskNext/PlayIntegrityFix/Shamiko and it works fine now, don't know why it didn't work with kitsune
> > 
> > It worked for me with alpha+zygisk next+shamiko from the telegram channel
> > 
> > Btw shamiko developer said it won't work in kitsune because of different way of loading zygisk
> 
> Could you attach the link for them😅


Channel:
https://t.me/magiskalpha

Shamiko module:
https://t.me/magiskalpha/646

Magisk Alpha:
https://t.me/magiskalpha/645

Zygisk next:
https://github.com/Dr-TSNG/ZygiskNext

But you have to turn off built in zygisk to use zygisk next


Apatch root worked also, without zygisk at all and with zygisk next with shamiko installed

**Comment by snake-4** [comment]
Closing in favor of #81.
